# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service # Name of the Service object
spec:
  # Type determines how the service is exposed:
  # LoadBalancer: Provisions a cloud load balancer (if on cloud provider). Easiest access.
  # NodePort: Exposes the service on each Node's IP at a static port. Good for local.
  # ClusterIP: Exposes the service on an internal IP, only reachable within the cluster (default).
  type: NodePort # Change to NodePort for Minikube/local if LoadBalancer isn't supported well
  selector:
    app: my-web-app # Selects Pods with this label to send traffic to
  ports:
  - protocol: TCP
    port: 80       # Port the Service will listen on (externally or internally)
    # Change targetPort to 3000 for the Node.js app
    targetPort: 5000 # Port on the Pods/Containers to forward traffic to <-- CHANGE TO 3000 FOR NODE.JS
    # If using type: NodePort, you can optionally specify a nodePort (range 30000-32767)
    # nodePort: 30080